SHAPE:
  ARC:
    1: "10" #"x"
    2: "20" #"y"
    3: "40" #"r"
    4: "50" #"theta1"
    5: "51" #"theta2"
  
  CIRCLE:
    0: "10" #: "x"
    1: "20" #: "y"
    2: "40" #: "r"

  LINE:
    0: "10" #"x1"
    1: "20" #"y1"
    2: "11" #"x2"
    3: "21" #"y2"
   
  LWPOLYLINE:
    0: "10" #"x"
    1: "20" #"y"
 
  POLYLINE:
    0: "VERTEX" #:
    1: "10"     #: "x"
    2: "20"     #: "y"

